version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: usuario-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: usuariosdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: